version: 0.2

phases:
  install:
    commands:
      - echo Installing...

  build:
    commands:
      - echo Build started
      - ls -la   # VERY IMPORTANT (debug)

artifacts:
  files:
    - '**/*'
  base-directory: .
